spring.application.name=productos-grpc
spring.main.web-application-type=none
spring.main.keep-alive=true

spring.datasource.url=${DB_URL:jdbc:sqlserver://127.0.0.1:1433;databaseName=poli;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:poli}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

grpc.server.port=${GRPC_PORT:9090}
